services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql8
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root123456
#      MYSQL_DATABASE: app_db
#      MYSQL_USER: app_user
#      MYSQL_PASSWORD: app_pass
#      TZ: Asia/Shanghai
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./mysql/data:/var/lib/mysql
#      - ./mysql/conf.d:/etc/mysql/conf.d
#      - ./mysql/init:/docker-entrypoint-initdb.d
#    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "26379:6379"   # Redis 服务端口
    environment:
      - REDIS_ARGS=--requirepass 123456
    volumes:
      - ./redis/data:/data

  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    restart: always
    ports:
      - "8888:8080"
    volumes:
      - ./searxng/config:/etc/searxng/
      - ./searxng/data:/var/cache/searxng/
